name: "issue_comment"
on:
  issue_comment:
    types: [created]
  

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: run-something
      if: github.event.issue.comment.body == "testCLA" && github.event.issue.comment.author == "ibakshay"
        run: echo run CLA flow
    
      
